import fs from 'node:fs/promises';
import path from 'node:path';
import { ROOT } from './lib/paths.js';
import { pool } from '../apps/api/src/db/pool.js';
import { listPokemonSql, POKEMON_DETAIL_SQL } from '../apps/api/src/queries/pokemon.queries.js';
import { listItemsSql, ITEM_DETAIL_SQL } from '../apps/api/src/queries/items.queries.js';
import { DEFAULT_PAGE_SIZE } from '../apps/api/src/constants.js';

// The statements come from the API's own query builders, not from copies. A plan quoted
// here is therefore a plan for the query the API actually issues.
// Imported rather than written as 24, so raising the default page size re-plans at the
// size the API actually serves. constants.js already says to re-run this script when it
// changes; this is that coupling encoded instead of remembered.
const PAGE = { limit: DEFAULT_PAGE_SIZE, offset: 0 };

const queries = [
  {
    name: 'pokemon list, no filter, page 1',
    note: 'The default wiki view. Watch the lateral: loops must equal the page size, not the match count.',
    ...pick(listPokemonSql(PAGE)),
  },
  {
    name: 'pokemon list, bucket=common',
    note: 'Decides whether pokemon_spawns_bucket_idx earns its place.',
    ...pick(listPokemonSql({ ...PAGE, buckets: ['common'] })),
  },
  {
    name: 'pokemon list, bucket=common,rare',
    note: 'Two-member bucket list. = ANY(...) rather than a single equality.',
    ...pick(listPokemonSql({ ...PAGE, buckets: ['common', 'rare'] })),
  },
  {
    name: 'pokemon list, biome=#cobblemon:is_overworld',
    note: 'Array overlap. Should reach pokemon_spawns_biomes_idx, the GIN index.',
    ...pick(listPokemonSql({ ...PAGE, biomes: ['#cobblemon:is_overworld'] })),
  },
  {
    name: 'pokemon list, biome=#cobblemon:is_overworld,#minecraft:is_nether',
    note: 'Two-member biome list, still one GIN-served array-overlap predicate.',
    ...pick(listPokemonSql({ ...PAGE, biomes: ['#cobblemon:is_overworld', '#minecraft:is_nether'] })),
  },
  {
    name: 'pokemon list, bucket=common and biome=#cobblemon:is_overworld',
    note: 'Both dimensions at once - two separate EXISTS subqueries, ANDed.',
    ...pick(listPokemonSql({ ...PAGE, buckets: ['common'], biomes: ['#cobblemon:is_overworld'] })),
  },
  {
    name: 'pokemon list, search=abra',
    note: 'The full-text branch, four characters or more.',
    ...pick(listPokemonSql({ ...PAGE, search: 'abra' })),
  },
  {
    name: 'pokemon detail, abra',
    note: 'Unique index lookup plus one lateral. loops greater than 1 would be a bug.',
    text: POKEMON_DETAIL_SQL,
    params: ['abra'],
  },
  {
    name: 'items list, search=potion',
    note: 'The GIN search vector plus the printf-name exclusion.',
    ...pick(listItemsSql({ ...PAGE, search: 'potion' })),
  },
  {
    name: 'items list, sourceCategory=berries-berry-items',
    note: 'The filter the item chips use. ADR 0002.',
    ...pick(listItemsSql({ ...PAGE, sourceCategory: 'berries-berry-items' })),
  },
  {
    name: 'item detail, cobblemon:ability_capsule',
    note: 'Unique index lookup.',
    text: ITEM_DETAIL_SQL,
    params: ['cobblemon:ability_capsule'],
  },
];

function pick({ text, params }) {
  return { text, params };
}

const sections = [];

try {
  for (const query of queries) {
    const { rows } = await pool.query(
      `EXPLAIN (ANALYZE, BUFFERS) ${query.text}`,
      query.params,
    );
    const plan = rows.map((row) => row['QUERY PLAN']).join('\n');

    const loops = [...plan.matchAll(/loops=(\d+)/g)].map((m) => Number(m[1]));
    const scans = [...plan.matchAll(/(Seq Scan|Index Scan|Bitmap Index Scan|Index Only Scan) on (\w+)/g)]
      .map((m) => `${m[1]} on ${m[2]}`);

    // Math.max of an empty array is -Infinity, which would be written into the report as a
    // number rather than being loudly absent - and this column is the one the contract
    // names as the thing to watch.
    const maxLoops = loops.length ? Math.max(...loops) : null;

    console.log(`[plan] ${query.name}`);
    console.log(`        max loops ${maxLoops ?? 'not reported'}, scans: ${[...new Set(scans)].join(', ') || 'none named'}`);

    sections.push({ ...query, plan, maxLoops, scans: [...new Set(scans)] });
  }

  const report = [
    '# Query plans',
    '',
    `Generated by \`npm run explain\` (\`scripts/explain-api.js\`) on ${new Date().toISOString().slice(0, 10)}.`,
    '**Do not hand-edit.**',
    '',
    'Every statement below is produced by the API\'s own query builders in',
    '`apps/api/src/queries/`, so these are plans for the queries the API issues, not for',
    'copies of them. `CLAUDE.md` and `03-database/schema.md` both require a plan before any',
    'index is added or dropped.',
    '',
    '| Query | Max loops | Scans |',
    '|---|---|---|',
    ...sections.map((s) => `| ${s.name} | ${s.maxLoops ?? 'not reported'} | ${s.scans.join(', ') || 'none named'} |`),
    '',
    ...sections.flatMap((s) => [
      `## ${s.name}`,
      '',
      s.note,
      '',
      '```sql',
      s.text.trim(),
      '```',
      '',
      '```',
      s.plan,
      '```',
      '',
    ]),
  ].join('\n');

  await fs.writeFile(path.join(ROOT, 'ground-truth/reports/query-plans.md'), `${report}\n`, 'utf8');
  console.log('\nWrote ground-truth/reports/query-plans.md');
} finally {
  await pool.end();
}
